"""Current-patch MetaTFT catalog, state, and encoder utilities."""

from mini_tft.metatft.catalog import (
    CatalogAugment,
    CatalogItem,
    CatalogMetadata,
    CatalogTag,
    CatalogTrait,
    CatalogUnit,
    CompStageLine,
    MetaTFTCatalog,
    MetaTFTComp,
    TraitBreakpoint,
    UnitItemBuild,
    build_catalog_from_comp_records,
    load_catalog_from_comp_strength,
    load_catalog_from_payload,
)
from mini_tft.metatft.encoders import (
    STAGE_LINE_SPECS,
    CurrentBoardEncoder,
    EncodedBoardState,
    EncodedStageLine,
    derive_stage_line_states,
    final_board_state,
)
from mini_tft.metatft.metrics import TopCompMatch, top_comp_match_report
from mini_tft.metatft.planner import (
    CandidateTransition,
    CurrentPatchPlannerScorer,
    ScoredTransition,
    build_shop_bench_board_transitions,
)
from mini_tft.metatft.policy import (
    CurrentPatchShopEconPolicy,
    PolicyTurnPlan,
    ShopEconPolicyConfig,
)
from mini_tft.metatft.schema import CurrentBoardState, CurrentBoardUnit
from mini_tft.metatft.value_training import (
    BoardValueBatch,
    CurrentPatchRankingReport,
    CurrentPatchValueConfig,
    CurrentPatchValueNet,
    CurrentPatchValueTrainReport,
    build_value_training_batch,
    ranking_report,
    train_current_patch_value_model,
)

__all__ = [
    "CandidateTransition",
    "CatalogMetadata",
    "CatalogAugment",
    "CatalogItem",
    "CatalogTag",
    "CatalogTrait",
    "CatalogUnit",
    "CompStageLine",
    "CurrentBoardEncoder",
    "CurrentPatchPlannerScorer",
    "CurrentPatchShopEconPolicy",
    "CurrentPatchRankingReport",
    "CurrentBoardState",
    "CurrentBoardUnit",
    "CurrentPatchValueConfig",
    "CurrentPatchValueNet",
    "CurrentPatchValueTrainReport",
    "EncodedBoardState",
    "EncodedStageLine",
    "MetaTFTCatalog",
    "MetaTFTComp",
    "PolicyTurnPlan",
    "ScoredTransition",
    "ShopEconPolicyConfig",
    "STAGE_LINE_SPECS",
    "TraitBreakpoint",
    "UnitItemBuild",
    "BoardValueBatch",
    "TopCompMatch",
    "build_catalog_from_comp_records",
    "build_shop_bench_board_transitions",
    "build_value_training_batch",
    "derive_stage_line_states",
    "final_board_state",
    "load_catalog_from_comp_strength",
    "load_catalog_from_payload",
    "ranking_report",
    "top_comp_match_report",
    "train_current_patch_value_model",
]
